### ISSUE TITLE
Run Command ctrl-s and ctrl-return not working

### ISSUE THREAD

**Issue by Guzzii** [wmvanvliet/vim-ipython#3]
Hi Marijn, I really like the run-cell feature you added. I was testing wmvanvliet/vim-ipython with nvim on macOS. F5 seemed working as expected, but not ctrl-s and ctrl-return, which works fine when I was using ivanov/vim-ipython. I tried the fix mentioned in [Known Issues](https://github.com/wmvanvliet/vim-ipython#known-issues). It didn't help.

Please feel free to let me know what information would be helpful to identify the root cause. Thank you in advance.

**Comment by wmvanvliet** [comment]
Look like I've been messing up the default keybindings. Until I fix them, you can define your own and get everything running. See here:

https://github.com/wmvanvliet/vim-ipython/blob/master/ftplugin/python/ipy.vim#L198

**Comment by Guzzii** [comment]
Thanks for replying. I figured ctrl-s out when comparing with the ivanov/vim-ipython. I added following to ipy.vim,

`map  <buffer> <silent> <C-s>          <Plug>(IPython-RunLine)`
`imap <buffer> <silent> <C-s>          <C-o><Plug>(IPython-RunLine)`
`xmap <buffer> <silent> <C-s>          <Plug>(IPython-RunLines)`


But I still can't get ctrl-return working.

**Comment by wmvanvliet** [comment]
add:

    map  <buffer> <silent> <C-Return> <Plug>(IPython-RunCell)

**Comment by scholi** [comment]
Somehow this issue is still not fixed. Can someone merge it please?

**Comment by wmvanvliet** [comment]
done!
